[package]
name = "AdventOfCode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day_01"
path = "src/Day_01/main.rs"

[[bin]]
name = "day_02"
path = "src/Day_02/main.rs"